# Generated by Django 6.1.1 on 2026-09-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=150)),
                ('job_code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ctc_offered', models.DecimalField(decimal_places=2, help_text='Annual CTC in LPA (Lakhs Per Annum)', max_digits=6)),
                ('eligibility_criteria', models.CharField(blank=True, max_length=255)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='placements.company')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('interview_status', models.CharField(choices=[('NOT_SCHEDULED', 'Not scheduled'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='NOT_SCHEDULED', max_length=15)),
                ('selection_status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On hold')], default='PENDING', max_length=15)),
                ('offer_ctc', models.DecimalField(blank=True, decimal_places=2, help_text='Final offer CTC in LPA, if selected', max_digits=6, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.jobposting')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
