# Generated by Django 6.1.1 on 2026-09-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interviewer_name', models.CharField(max_length=120)),
                ('round_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'HR')], default='TECHNICAL', max_length=10)),
                ('attended', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score out of 10', null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='batches.batch')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='students.student')),
            ],
            options={
                'ordering': ['-interview_date', '-interview_time'],
            },
        ),
    ]
