# Generated by Django 6.1.1 on 2026-10-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('batches', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'batch', 'date')},
        ),
    ]
